# Generated by Django 5.1.2 on 2024-11-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='username',
            new_name='UserData',
        ),
    ]
