# Generated by Django 5.0.10 on 2024-12-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_task_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
