# Generated by Django 5.0.10 on 2024-12-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_timestampedmodel_order_product_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountedProduct',
            fields=[
            ],
            options={
                'ordering': ['-price'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('school.product_2',),
        ),
    ]
